### ISSUE TITLE
verticenilavu doesn't start the service in the rpm package

### ISSUE THREAD

**Issue by indykish** [megamsys/gitpackager#286]
@ranjithamca  Lets fix it up on monday.

**Comment by indykish** [comment]
@rajesh-rajagopal  Please work with platform (@vijaykanthm28 , if it goes beyond your boundary.

**Comment by rajesh-rajagopal** [comment]
@indykish Manually start the nilavu its run and i can see UI in browser.
RAILS_ENV=production bundle exec rake assets:precompile


instead of i can use sv stop unicorn & sv start unicorn it shows an error

[root@test-nilavu getty-5]# sv start unicorn
warning: unicorn: unable to open supervise/ok: file does not exist

Use the vm : 192.168.0.132
username & password is megam
